@startuml
'https://plantuml.com/sequence-diagram

skinparam responseMessageBelowArrow true

participant EntryPoint

create IndexAdvisor
EntryPoint -> IndexAdvisor : create

EntryPoint -> IndexAdvisor : prepare()
activate IndexAdvisor

create Schema

IndexAdvisor -> Schema : create
activate Schema
Schema -> IndexAdvisor : объекты схемы
deactivate Schema

create WorkloadGenerator
IndexAdvisor -> WorkloadGenerator : create
activate WorkloadGenerator
WorkloadGenerator -> IndexAdvisor : нагрузка, список атрибутов \nдля индексирования
deactivate WorkloadGenerator

IndexAdvisor -> IndexAdvisor : перестановки атрибутов \nW_max

IndexAdvisor -> IndexAdvisor : оценка размеров индексов

IndexAdvisor -> EntryPoint : ok
deactivate IndexAdvisor


EntryPoint -> IndexAdvisor : make_env()
activate IndexAdvisor

create ActionManager
IndexAdvisor -> ActionManager : create
activate ActionManager
ActionManager -> IndexAdvisor : ok
deactivate ActionManager

create ObservationManager
IndexAdvisor -> ObservationManager : create
activate ObservationManager
ObservationManager -> IndexAdvisor : ok
deactivate ObservationManager

create RewardManager
IndexAdvisor -> RewardManager : create
activate RewardManager
RewardManager -> IndexAdvisor : ok
deactivate RewardManager

create Env
IndexAdvisor -> Env : gym.make(ActionManager, ObservationManager, RewardManager)
activate Env
Env -> IndexAdvisor : ok
deactivate Env

IndexAdvisor -> EntryPoint : Env
deactivate IndexAdvisor

create MaskablePPO
EntryPoint -> MaskablePPO : create(Env)
activate MaskablePPO
MaskablePPO -> EntryPoint : model
deactivate MaskablePPO

EntryPoint -> IndexAdvisor : save(model)
IndexAdvisor -> EntryPoint : ok

EntryPoint -> MaskablePPO : learn()
activate MaskablePPO
MaskablePPO -> EntryPoint : ok
deactivate MaskablePPO

EntryPoint -> IndexAdvisor : генерация отчета
IndexAdvisor -> EntryPoint : report.txt

@enduml